name: IC-RainbowBeacons
main: bl4ckscor3.plugin.icrb.ICRainbowBeacons
version: 0.3
author: [bl4ckscor3]
description: Adds Rainbow Beacons!
commands:
    rb:
        description: Main command.
        usage: /rb <add|abort|remove|start|stop|restart>
